// <auto-generated />
using System;
using BankAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankAPI.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankAPI.Models.Account", b =>
                {
                    b.Property<Guid?>("id_account")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("accountNum")
                        .HasColumnType("text");

                    b.Property<decimal>("balance")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("bankId")
                        .HasColumnType("uuid");

                    b.Property<string>("clientdocNumber")
                        .HasColumnType("text");

                    b.Property<string>("currency")
                        .HasColumnType("text");

                    b.Property<string>("docNumber")
                        .HasColumnType("text");

                    b.HasKey("id_account");

                    b.HasIndex("bankId");

                    b.HasIndex("clientdocNumber");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankAPI.Models.Bank", b =>
                {
                    b.Property<Guid?>("bankCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("adress")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("bankCode");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BankAPI.Models.Client", b =>
                {
                    b.Property<string>("docNumber")
                        .HasColumnType("text");

                    b.Property<string>("docType")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("docNumber");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BankAPI.Models.Transfer", b =>
                {
                    b.Property<string>("id_transaction")
                        .HasColumnType("text");

                    b.Property<string>("accountNum")
                        .HasColumnType("text");

                    b.Property<Guid?>("accountid_account")
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<string>("clientdocNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("docNumber")
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .HasColumnType("text");

                    b.HasKey("id_transaction");

                    b.HasIndex("accountid_account");

                    b.HasIndex("clientdocNumber");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("BankAPI.Models.Account", b =>
                {
                    b.HasOne("BankAPI.Models.Bank", "bank")
                        .WithMany("Accounts")
                        .HasForeignKey("bankId");

                    b.HasOne("BankAPI.Models.Client", "client")
                        .WithMany("Accounts")
                        .HasForeignKey("clientdocNumber");

                    b.Navigation("bank");

                    b.Navigation("client");
                });

            modelBuilder.Entity("BankAPI.Models.Transfer", b =>
                {
                    b.HasOne("BankAPI.Models.Account", "account")
                        .WithMany("Transfers")
                        .HasForeignKey("accountid_account");

                    b.HasOne("BankAPI.Models.Client", "client")
                        .WithMany("Transfers")
                        .HasForeignKey("clientdocNumber");

                    b.Navigation("account");

                    b.Navigation("client");
                });

            modelBuilder.Entity("BankAPI.Models.Account", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("BankAPI.Models.Bank", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BankAPI.Models.Client", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
